
services:

  system-tests:
    container_name: system-tests
    build:
      context: .
      dockerfile: ./src/Micro.Web/Dockerfile
      target: system-tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DOTNET_NOLOGO=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - DOTNET_NUGET_SIGNATURE_VERIFICATION=false
      - Logging:LogLevel:Default=Warning
      - DB_HOST=db
      - GITHUB_ACTIONS=${GITHUB_ACTIONS:-FALSE}
    entrypoint:
      - dotnet
      - test
      - --collect:"XPlat Code Coverage"
      - --configuration=Release
      - --verbosity=quiet
      - --filter=Type=System
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"