version: '3.8'

services:
  
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./src/Micro.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DOTNET_NOLOGO=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - Logging:LogLevel:Default=Warning
      - DB_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"