services:

  unit-tests:
    container_name: unit-tests
    build:
      context: .
      dockerfile: ./src/Micro.Web/Dockerfile
      target: unit-tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - DOTNET_NOLOGO=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - DOTNET_NUGET_SIGNATURE_VERIFICATION=false
      - Logging:LogLevel:Default=Warning
      - GITHUB_ACTIONS=${GITHUB_ACTIONS:-FALSE}
    entrypoint:
      - dotnet 
      - test 
      - --collect:"XPlat Code Coverage"
      - --configuration=Release
      - --verbosity=quiet 
      - --filter=Type=Unit