name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Version
        id: version
        run: |
          dotnet tool install --global minver-cli --version 5.0.0
          echo "VERSION=$(minver)" >> "$GITHUB_ENV"

      - name: Test
        run: ./run-docker-compose-test.sh

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GHCR
        env:
          ORIGINAL: microsaas-web
          IMAGE: microsaas
          OWNER: peterkneale
          REPO: microsaas
        run: |
          docker tag $ORIGINAL ghcr.io/$OWNER/$REPO/$IMAGE:$VERSION
          docker tag $ORIGINAL ghcr.io/$OWNER/$REPO/$IMAGE:latest
          docker push ghcr.io/$OWNER/$REPO/$IMAGE:$VERSION
          docker push ghcr.io/$OWNER/$REPO/$IMAGE:latest

      - name: Release
        uses: softprops/action-gh-release@v2

