name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Install version tool
      id: version
      run: dotnet tool install --global minver-cli --version 5.0.0

    - name: Calculate version
      id: version
      run: echo "VERSION=$(minver)" >> "$GITHUB_ENV"

    - name: Test
      run: ./run-docker-compose-test.sh

