name: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  
  build:
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: 'false'

      - name: Build
        run: ./run-docker-compose-build.sh

      - name: Test
        run: ./run-docker-compose-test.sh

      - name: Display
        run: docker images
            
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version number
        id: version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Publish to GHCR
        env:
          ORIGINAL: modular_monolith_saas-web
          IMAGE: modular_monolith_saas
          OWNER: peterkneale
          REPO: modular_monolith_saas
          VERSION: ${{ steps.version.outputs.tag }}
        run: |
          docker tag $ORIGINAL ghcr.io/$OWNER/$REPO/$IMAGE:$VERSION
          docker tag $ORIGINAL ghcr.io/$OWNER/$REPO/$IMAGE:latest
          docker push ghcr.io/$OWNER/$REPO/$IMAGE:$VERSION
          docker push ghcr.io/$OWNER/$REPO/$IMAGE:latest

      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.tag }}
          generateReleaseNotes: true
